# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/event-driven-playground
spring.datasource.username=event-driven-playground
spring.datasource.password=event-driven-playground
spring.datasource.driver-class-name=org.postgresql.Driver

# (volitelné) JPA/Hibernate pro experimenty
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Kafka ---
spring.kafka.bootstrap-servers=localhost:9092

# Producer (volitelné, ale v CQRS se hodí)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer
spring.kafka.consumer.group-id=event-driven-playground-demo
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# (volitelné) aby se poslouchalo i na více topic? jednodu?e
spring.kafka.listener.missing-topics-fatal=false